//! ROM regression harness (task #8).
//!
//! Each test loads a small hand-rolled SH-2 program into a MemBus, runs
//! it for a fixed number of steps, and hashes the post-execution state.
//! The hashes are committed as goldens — any silent drift in opcode
//! semantics, cycle counting, exception dispatch, or routing will flip
//! exactly the affected test, pointing straight at the regression.
//!
//! Golden values were generated by running this harness against the
//! known-good interpreter at the time task #8 landed. If a deliberate
//! semantic change is needed (extremely rare past M1), rerun the test
//! once with `--nocapture` to read the new actual hash and update the
//! `expected` constant.

// `state_digest` takes a slice of memory-region ranges; passing a single
// region as `&[a..b]` is intentional, not a mis-initialised range-vec.
#![allow(clippy::single_range_in_vec_init)]

use sh2::Cpu;
use sh2::harness::{MemBus, state_digest};

const PC0: u32 = 0x0000_1000;
const SP0: u32 = 0x0000_8000;

fn fresh(prog: &[u16]) -> (Cpu, MemBus) {
    let mut bus = MemBus::new(64 * 1024);
    bus.load_program(PC0, prog);
    let mut cpu = Cpu::new();
    cpu.regs.pc = PC0;
    cpu.regs.r[15] = SP0;
    (cpu, bus)
}

fn run(cpu: &mut Cpu, bus: &mut MemBus, steps: usize) {
    for _ in 0..steps {
        cpu.step(bus);
    }
}

/// Print and compare; on mismatch the failure message includes both the
/// expected and actual values so a deliberate update is a one-step edit.
#[track_caller]
fn check(label: &str, actual: u64, expected: u64) {
    assert_eq!(
        actual, expected,
        "{label}: golden hash mismatch (expected {expected:#018x}, got {actual:#018x}). \
         If this was intentional, update the constant."
    );
}

#[test]
fn rom_arith_loop_sums_n_minus_1_down_to_zero() {
    // R3 := sum of N..1 using a DT loop, then settles.
    //   MOV #5, R3        ; sum
    //   MOV #5, R4        ; counter
    //   loop:
    //   ADD R4, R3
    //   DT  R4
    //   BF  loop          ; back 2 instructions
    //   NOP
    //   NOP
    let prog = [
        0xE305_u16, 0xE405, // MOV #5,R3 ; MOV #5,R4
        0x334C, // ADD R4, R3 (n=3, m=4)
        0x4410, // DT R4
        0x8BFC, // BF -4 (back to ADD)
        0x0009, 0x0009,
    ];
    let (mut cpu, mut bus) = fresh(&prog);
    run(&mut cpu, &mut bus, 20);
    check(
        "arith_loop",
        state_digest(&cpu, &bus, &[PC0..PC0 + 0x20]),
        0x17272dd7b3b98f02,
    );
    // Cross-check: 5 + (5+4+3+2+1) = 5 + 15 = 20.
    assert_eq!(cpu.regs.r[3], 20);
}

#[test]
fn rom_load_store_round_trip_via_pre_dec_post_inc() {
    // Push 4 values onto the stack (pre-decrement store), then pop them
    // back in reverse via post-increment load.
    //   MOV #1, R0 ; MOV.L R0, @-R15 ; (×4 for values 1..4)
    //   MOV.L @R15+, R0 ; (×4)
    let prog = [
        0xE001, 0x2F06, // 1
        0xE002, 0x2F06, // 2
        0xE003, 0x2F06, // 3
        0xE004, 0x2F06, // 4
        // Pop into R13, R12, R11, R10 in that order via MOV.L @R15+,Rn.
        // (Popping into R15 first would clobber SP and break the chain —
        // hardware-correct behaviour on SH-2 when Rn == Rm, but useless.)
        0x6DF6, 0x6CF6, 0x6BF6, 0x6AF6, 0x0009,
    ];
    let (mut cpu, mut bus) = fresh(&prog);
    run(&mut cpu, &mut bus, prog.len());
    check(
        "load_store",
        state_digest(&cpu, &bus, &[(SP0 - 16)..SP0]),
        0xb382788942accf2b,
    );
    // Stack held [4,3,2,1] from low to high. Pops in that order land in
    // R13, R12, R11, R10.
    assert_eq!(cpu.regs.r[13], 4);
    assert_eq!(cpu.regs.r[12], 3);
    assert_eq!(cpu.regs.r[11], 2);
    assert_eq!(cpu.regs.r[10], 1);
    assert_eq!(cpu.regs.r[15], SP0, "stack restored");
}

#[test]
fn rom_branch_taken_and_not_taken_paths() {
    // CMP/EQ then BT/BF mix to exercise both branch outcomes and delay
    // slots. SETT in the not-taken arm proves both arms execute.
    //   MOV #1, R1
    //   MOV #1, R2
    //   CMP/EQ R1, R2     ; T=1
    //   BT/S +0           ; taken, slot executes
    //   ADD R1, R2        ; slot — R2 becomes 2, then we land at next CMP
    //   CMP/EQ R1, R2     ; T=0 (1 vs 2)
    //   BT +0             ; not taken (T=0); fall through to MOV
    //   MOV #9, R5
    //   NOP
    let prog = [
        0xE101, 0xE201, // MOV #1,R1 ; MOV #1,R2
        0x3210, // CMP/EQ R1,R2 → T=1
        0x8D00, // BT/S +0 → taken, slot runs, lands at next CMP
        0x321C, // ADD R1,R2 (slot)
        0x3210, // CMP/EQ R1,R2 → T=0 (1 vs 2)
        0x8900, // BT +0 → not taken, falls through
        0xE509, // MOV #9,R5
        0x0009,
    ];
    let (mut cpu, mut bus) = fresh(&prog);
    run(&mut cpu, &mut bus, prog.len());
    check(
        "branch_mix",
        state_digest(&cpu, &bus, &[]),
        0x8d0ba4de7b8d6b9d,
    );
    assert_eq!(cpu.regs.r[5], 9);
}

#[test]
fn rom_trapa_handler_round_trip() {
    // TRAPA #5 vectors to handler, which sets R7 and RTEs back.
    //   PC0+0  TRAPA #5
    //   PC0+2  MOV #1, R6   (post-return)
    //   handler at 0x6000:
    //   PC0+...  MOV #42, R7
    //   PC0+...  RTE
    //   PC0+...  NOP (RTE slot)
    let prog = [
        0xC305, // TRAPA #5
        0xE601, // MOV #1, R6 (returned to)
        0x0009,
    ];
    let (mut cpu, mut bus) = fresh(&prog);
    cpu.regs.vbr = 0x0000_5000;
    bus.write_u32(0x5000 + 5 * 4, 0x0000_6000); // vector 5 → handler
    bus.load_program(
        0x0000_6000,
        &[
            0xE72A, // MOV #42, R7
            0x002B, // RTE
            0x0009, // RTE delay slot
        ],
    );
    run(&mut cpu, &mut bus, 6);
    check(
        "trapa_round_trip",
        state_digest(&cpu, &bus, &[(SP0 - 8)..SP0]),
        0xcb4f7b1f6378f718,
    );
    assert_eq!(cpu.regs.r[7], 42);
    assert_eq!(cpu.regs.r[6], 1, "fell through to post-return MOV");
    assert_eq!(cpu.regs.r[15], SP0, "stack restored after RTE");
}

#[test]
fn rom_multiply_accumulate_chain() {
    // Two MAC.L iterations summing products. Confirms the MAC pipeline
    // and post-increment behaviour are stable.
    //   MOV.L @(0,PC), R1    ; ptr A
    //   MOV.L @(1,PC), R2    ; ptr B
    //   CLRMAC
    //   MAC.L @R1+, @R2+
    //   MAC.L @R1+, @R2+
    //   NOP
    //   .literal A_ptr
    //   .literal B_ptr
    let prog = [
        0xD104, 0xD204, // (disps 4 and 4 — alignment masks resolve later)
        0x0028, // CLRMAC
        0x021F, // MAC.L @R1+, @R2+ (n=2, m=1)
        0x021F, 0x0009, 0x0009, // padding so literals are 4-aligned
        0x0009,
    ];
    let (mut cpu, mut bus) = fresh(&prog);
    // Compute literal addresses: for MOV.L @(4,PC),R1 at PC0+0:
    //   addr = (PC0 + 4 + 16) & ~3 = PC0 + 0x14
    // For MOV.L @(4,PC),R2 at PC0+2:
    //   addr = (PC0 + 2 + 4 + 16) & ~3 = (PC0 + 0x16) & ~3 = PC0 + 0x14
    //   — same as R1, so use different disp on the second.
    // Rebuild the program with disps 4 and 5:
    bus.load_program(
        PC0,
        &[
            0xD104, // MOV.L @(4,PC),R1 → PC0+0x14
            0xD205, // MOV.L @(5,PC),R2 → PC0+0x18
            0x0028, 0x021F, 0x021F, 0x0009, 0x0009, 0x0009,
        ],
    );
    bus.write_u32(PC0 + 0x14, 0x0000_3000); // A ptr
    bus.write_u32(PC0 + 0x18, 0x0000_4000); // B ptr
    bus.write_u32(0x3000, 3);
    bus.write_u32(0x3004, 5);
    bus.write_u32(0x4000, 7);
    bus.write_u32(0x4004, 11);
    run(&mut cpu, &mut bus, 6);
    check(
        "mac_chain",
        state_digest(&cpu, &bus, &[0x3000..0x3008, 0x4000..0x4008]),
        0xd17dad786d952bd7,
    );
    assert_eq!(cpu.regs.macl, 3 * 7 + 5 * 11, "MACL = 76");
    assert_eq!(cpu.regs.mach, 0);
}
